### ISSUE TITLE
When focused, `:invalid` fields have `.field-light:focus` box shadow and `.field-light:invalid` border

### ISSUE THREAD

**Issue by pletcher** [basscss/color-forms#4]
![screen shot 2015-06-26 at 10 27 36 am](https://cloud.githubusercontent.com/assets/2015049/8379427/fd0604d0-1bed-11e5-9653-3766b636b271.png)

It looks like there's a `.field-light.is-error:focus` line, but no analogous `.field-light:invalid:focus` selector, which would fix the issue (looking at https://github.com/basscss/color-forms/blob/master/index.css#L52-55).

**Comment by jxnblk** [comment]
Thanks. I'll push out a fix for the beta version, which will be part of Basscss v7.
